### PR TITLE
Fix double bucket in URL when location is auto (fixes #8)

### LINKED ISSUE #8: File larger than 5MB returns incorrect location
I believe this is related to https://github.com/strapi/strapi/issues/15144

I am uploading 2 files, one is 2MB, another is 20MB. The 2MB correctly uploads, while the 20MB does not.

I added some debug logs in the plugin:

image

And for the small image, this is what is shows:

```
UPLOAD {
  name: 'output_lq_428a81a1ea.webm',
  alternativeText: undefined,
  caption: undefined,
  folder: null,
  folderPath: '/',
  hash: 'output_lq_428a81a1ea_42941346e6',
  ext: '.webm',
  mime: 'video/webm',
  size: 2470.86,
  tmpWorkingDirectory: '/tmp/strapi-upload-8SormW',
}
DATA {
  Key: 'output_lq_428a81a1ea_42941346e6.webm',
  ContentType: 'video/webm'
}
DONE {
  ETag: '"ef1526687da17f8c61ce7395b76ab5ec"',
  VersionId: '7e76d93598e37c650edf9aa70c33b76c',
  Location: 'https://xxx.yyy.r2.cloudflarestorage.com/xxx/output_lq_428a81a1ea_42941346e6.webm',
  key: 'output_lq_428a81a1ea_42941346e6.webm',
  Key: 'output_lq_428a81a1ea_42941346e6.webm',
  Bucket: 'xxx'
}
```

And for the large:
```
UPLOAD {
  name: 'output_hq_e61e3a8ffe.webm',
  alternativeText: undefined,
  caption: undefined,
  folder: null,
  folderPath: '/',
  hash: 'output_hq_e61e3a8ffe_7d90a26f80',
  ext: '.webm',
  mime: 'video/webm',
  size: 24595.52,
  tmpWorkingDirectory: '/tmp/strapi-upload-VzJ6EC',
}
DATA {
  Key: 'output_hq_e61e3a8ffe_7d90a26f80.webm',
  ContentType: 'video/webm'
}
DONE {
  VersionId: '7e76d9357c86a1d13a406f8300edeb86',
  Location: 'auto',
  Bucket: 'xxx',
  Key: 'xxx/output_hq_e61e3a8ffe_7d90a26f80.webm',
  ETag: '"52c7338c515190f7919dfbbeba2ca70c-5"'
}
```

Notes:
- `xxx` is the bucket
- The small file returns `Location` which is correct, the large file does not return `Location`
- The small file returns `Key` without a prefix, while the large file does have a prefix

Since I have `cloudflarePublicAccessUrl` set, the large file has the bucket twice in the final URL (`https://assets.domain.com/xxx/xxx/output_hq_e61e3a8ffe_7d90a26f80.webm`).

Seems like the fix for this is: When `Location` is `auto`, strip the bucket name + `/` from the `Key`, then assemble the URL.

Example:
image

```diff
diff --git a/node_modules/strapi-provider-cloudflare-r2/lib/index.js b/node_modules/strapi-provider-cloudflare-r2/lib/index.js
index 3209bf4..29ffc38 100644
--- a/node_modules/strapi-provider-cloudflare-r2/lib/index.js
+++ b/node_modules/strapi-provider-cloudflare-r2/lib/index.js
@@ -53,12 +52,20 @@ module.exports = {
             if (err) {
               return reject(err);
             }
+
+            // Strip bucket name from key
+            const key = data.Key.startsWith(`${config.params.Bucket}/`)
+              ? data.Key.replace(`${config.params.Bucket}/`, "")
+              : data.Key;
+
             // Set the bucket file url.
             // If there is a Custom endpoint for data access set, replace the upload endpoint with the read enpoint URL
-            if(config.cloudflarePublicAccessUrl){
-              file.url = config.cloudflarePublicAccessUrl.replace(/\/$/g,'')+'/'+data.Key;
+            if (config.cloudflarePublicAccessUrl) {
+              file.url = config.cloudflarePublicAccessUrl.replace(/\/$/g, "") + "/" + key;
+            } else if (data.Location !== "auto") {
+              file.url = data.Location;
             } else {
-              file.url = data.Location
+              // TODO: Handle missing location
             }

             // check if https is included in file URL

```

This fix seems to solve the issue for me for all cases.

### PR DESCRIPTION
**Pull request by Cretezy**
Fixed https://github.com/trieb-work/strapi-provider-cloudflare-r2/issues/8

Not sure what behavior should be when `cloudflarePublicAccessUrl` is not set and `Location` is `auto`, since we have no way of building the result URL.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -53,12 +53,23 @@ module.exports = {
...
+
+            // Strip bucket name from key if Location is auto
+            const key = data.Location === 'auto' && data.Key.startsWith(`${config.params.Bucket}/`)
+              ? data.Key.replace(`${config.params.Bucket}/`, '')
+              : data.Key;
+
+            // Set the bucket file URL.
+            // If there is a custom endpoint for data access set, replace the upload endpoint with the read enpoint URL.
+            // Otherwise, use location returned from S3 API if it's not "auto"
+            if (config.cloudflarePublicAccessUrl) {
```
Comment (Cretezy) [inline lib/index.js:71]: I think requiring `cloudflarePublicAccessUrl` to be set is the safest way to handle this case, as using `Key` is the only way we can guaranty to be able to build a URL.

File: lib/index.js [hunk 2]
```diff
@@ -53,12 +53,23 @@ module.exports = {
...
+              file.url = config.cloudflarePublicAccessUrl.replace(/\/$/g, '') + '/' + key;
+            } else if (data.Location !== 'auto') {
+              file.url = data.Location;
             } else {
-              file.url = data.Location
```
Comment (tilman) [inline lib/index.js:61]: If no `config.cloudflarePublicAccessUrl` ist set and `data.Location === 'auto'` we should throw an Error with a meaningfull message here so the Upload will fail. 

Best would be to also add a `process.emitWarning('...')` message on plugin bootstrap that uploads greater 5MB (https://developers.cloudflare.com/r2/objects/multipart-objects/) require config.cloudflarePublicAccessUrl to be set.

**Review by tilman — CHANGES_REQUESTED** [review]

File: lib/index.js (hunk 2 above)
Comment (Cretezy) [reply lib/index.js:61]: Since `cloudflarePublicAccessUrl` is already required for CSP, I think it would be useful to strongly recommend having it set. I will update the README too

I can add an error and `process.emitWarning` (when `cloudflarePublicAccessUrl` isn't set) though.

**Review by tilman — APPROVED** [review]
Thanks for your work and this great PR!
